# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resourcesmanagement', '0003_applicationdomaintable_resoucescover'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelTatble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, unique=True, verbose_name='\u59d3\u540d')),
                ('Phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u7535\u8bdd')),
                ('QQNunmber', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='QQ\u53f7')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': '\u8054\u7cfb\u4eba\u4fe1\u606f',
                'verbose_name_plural': '\u8054\u7cfb\u4eba\u4fe1\u606f',
            },
        ),
    ]
