# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resourcesmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktoSounceExportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressSegment', models.CharField(max_length=40, unique=True, verbose_name='\u56de\u6e90\u5730\u5740\u6bb5')),
                ('Province', models.CharField(max_length=40, verbose_name='\u7701\u4efd')),
                ('City', models.CharField(max_length=40, verbose_name='\u57ce\u5e02')),
                ('BackboneTransmission', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u9aa8\u5e72\u4f20\u8f93')),
                ('ASNumber', models.IntegerField(blank=True, null=True, verbose_name='AS\u53f7')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['AddressSegment'],
                'verbose_name': '\u56de\u6e90\u51fa\u53e3\u8868',
                'verbose_name_plural': '\u56de\u6e90\u51fa\u53e3\u8868',
            },
        ),
        migrations.CreateModel(
            name='CDNmanagementIpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagementIp', models.CharField(max_length=40, verbose_name='CDN\u7ba1\u7406IP')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'ordering': ['ManagementIp'],
                'verbose_name': 'cp\u7ba1\u7406\u5730\u5740\u8868',
                'verbose_name_plural': 'cp\u7ba1\u7406\u5730\u5740\u8868',
            },
        ),
        migrations.CreateModel(
            name='InternetResoucesTatble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternetAddsegment', models.CharField(max_length=40, verbose_name='\u4e92\u8054IP\u6bb5')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'ordering': ['InternetAddsegment'],
                'verbose_name': '\u4e92\u8054\u8d44\u6e90\u5217\u8868',
                'verbose_name_plural': '\u4e92\u8054\u8d44\u6e90\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='NetTypeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NetType', models.CharField(max_length=40, verbose_name='\u7f51\u7edc\u7c7b\u578b')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u7f51\u7edc\u7c7b\u578b\u8868',
            },
        ),
        migrations.CreateModel(
            name='WatoneExportIpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExportAddsegment', models.CharField(max_length=40, verbose_name='\u51fa\u53e3\u5730\u5740')),
                ('Province', models.CharField(max_length=40, verbose_name='\u7701\u4efd')),
                ('City', models.CharField(max_length=40, verbose_name='\u57ce\u5e02')),
                ('AccessOperator', models.CharField(max_length=40, verbose_name='\u63a5\u5165\u8fd0\u8425\u5546')),
                ('BackboneTransmission', models.CharField(max_length=40, verbose_name='\u9aa8\u5e72\u4f20\u8f93')),
                ('ASNumber', models.IntegerField(blank=True, null=True, verbose_name='AS\u53f7')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('NetworkType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPaddrmanagement.NetTypeTable', verbose_name='\u7f51\u7edc\u7c7b\u578b')),
            ],
            options={
                'ordering': ['ExportAddsegment'],
                'verbose_name': '\u534e\u901a\u51fa\u53e3\u5730\u5740\u5217\u8868',
                'verbose_name_plural': '\u534e\u901a\u51fa\u53e3\u5730\u5740\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='backtosounceexporttable',
            name='NetworkType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPaddrmanagement.NetTypeTable', verbose_name='\u7f51\u7edc\u7c7b\u578b'),
        ),
        migrations.AlterUniqueTogether(
            name='watoneexportiptable',
            unique_together=set([('ExportAddsegment',)]),
        ),
        migrations.AlterUniqueTogether(
            name='internetresoucestatble',
            unique_together=set([('InternetAddsegment',)]),
        ),
        migrations.AlterUniqueTogether(
            name='cdnmanagementiptable',
            unique_together=set([('ManagementIp',)]),
        ),
    ]
