# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPaddrmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtosounceexporttable',
            name='Remarks',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='cdnmanagementiptable',
            name='Remarks',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='internetresoucestatble',
            name='Remarks',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='watoneexportiptable',
            name='Remarks',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
