# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=40, verbose_name='\u59d3\u540d')),
                ('FileName', models.FileField(upload_to='./useruploadfile/', verbose_name='\u6587\u4ef6\u540d')),
                ('TableName', models.CharField(max_length=30, verbose_name='\u64cd\u4f5c\u5bf9\u8c61')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'ordering': ['UserName'],
                'verbose_name': '\u7528\u6237\u4e0a\u4f20\u6587\u4ef6',
                'verbose_name_plural': '\u7528\u6237\u4e0a\u4f20\u6587\u4ef6',
            },
        ),
    ]
