# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDomainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, verbose_name='\u57df\u540d')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['domain'],
                'verbose_name': '\u5e94\u7528\u57df\u540d\u8868',
                'verbose_name_plural': '\u5e94\u7528\u57df\u540d\u8868',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=30, verbose_name='\u5e94\u7528')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['app'],
                'verbose_name': '\u5e94\u7528\u8868',
                'verbose_name_plural': '\u5e94\u7528\u8868',
            },
        ),
        migrations.CreateModel(
            name='CDNTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDN', models.CharField(max_length=30, verbose_name='CDN\u540d\u79f0')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['CDN'],
                'verbose_name': 'CDN\u8868',
                'verbose_name_plural': 'CDN\u8868',
            },
        ),
        migrations.CreateModel(
            name='ControlDomainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ControlDomain', models.CharField(max_length=30, verbose_name='\u8c03\u5ea6\u63a7\u5236\u57df\u540d')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'ordering': ['ControlDomain'],
                'verbose_name': '\u8c03\u5ea6\u63a7\u5236\u57df\u540d\u8868',
                'verbose_name_plural': '\u8c03\u5ea6\u63a7\u5236\u57df\u540d\u8868',
            },
        ),
        migrations.CreateModel(
            name='ControlIpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ControlIp', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u8c03\u5ea6ip')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'ordering': ['ControlIp'],
                'verbose_name': '\u8c03\u5ea6\u63a7\u5236ip\u8868',
                'verbose_name_plural': '\u8c03\u5ea6\u63a7\u5236ip\u8868',
            },
        ),
        migrations.CreateModel(
            name='CoverTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cover', models.CharField(max_length=50, verbose_name='\u8986\u76d6\u60c5\u51b5')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8986\u76d6\u60c5\u51b5',
                'verbose_name_plural': '\u8986\u76d6\u60c5\u51b5',
            },
        ),
        migrations.CreateModel(
            name='RegionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name='\u57df')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'ordering': ['region'],
                'verbose_name': 'CDN\u57df\u8868',
                'verbose_name_plural': 'CDN\u57df\u8868',
            },
        ),
        migrations.CreateModel(
            name='restype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restype', models.CharField(max_length=50, verbose_name='\u7c7b\u578b')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u57df\u540d\u7c7b\u578b\u8868',
                'verbose_name_plural': '\u57df\u540d\u7c7b\u578b\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cdntable',
            unique_together=set([('CDN',)]),
        ),
        migrations.AlterUniqueTogether(
            name='applicationtable',
            unique_together=set([('app',)]),
        ),
        migrations.AddField(
            model_name='applicationdomaintable',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.ApplicationTable', verbose_name='\u5e94\u7528'),
        ),
        migrations.AddField(
            model_name='applicationdomaintable',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.RegionTable', verbose_name='\u57df'),
        ),
        migrations.AddField(
            model_name='applicationdomaintable',
            name='res_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.restype', verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='applicationdomaintable',
            name='resoucescover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CoverTable', verbose_name='\u8986\u76d6\u60c5\u51b5'),
        ),
        migrations.AlterUniqueTogether(
            name='regiontable',
            unique_together=set([('region',)]),
        ),
        migrations.AlterUniqueTogether(
            name='controliptable',
            unique_together=set([('ControlIp',)]),
        ),
        migrations.AlterUniqueTogether(
            name='controldomaintable',
            unique_together=set([('ControlDomain',)]),
        ),
        migrations.AlterUniqueTogether(
            name='applicationdomaintable',
            unique_together=set([('domain', 'region', 'app')]),
        ),
    ]
